global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'cfguardian-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cfguardian-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8080']
    # Uncomment when app is ready
    # scrape_interval: 5s

